### PR TITLE
Release 3.0.1

### PR DESCRIPTION
**Pull request by Anduin2017**

### CODE REVIEW

**Comment by Anduin2017** [comment]
@xxyzz  Caution! Once merged, our `getMessages` API will enable our new skip system. Please achieve that soon!

**Review by xxyzz — APPROVED** [review]

**Comment by xxyzz** [comment]
@anduin2017 But it returns an incomplete json.

**Comment by Anduin2017** [comment]
Ohhh. WTF!? 

We shouldn't merge it yet. Could you please give me a curl command which could repro this issue?

**Comment by xxyzz** [comment]
`curl --cookie ".AspNetCore.Identity.Application=SuperSecretToken" https://dev.server.kahla.app/conversation/GetMessage\?id\=7\&messsageId\=-1\&take\=15`

**Comment by Anduin2017** [comment]
OK. Got it.

**Pull request merged**
